from pathlib import Path
import shutil
import subprocess
import tempfile
from typing import List

from simba.args.toolchain import Toolchain
from simba.log import loggy

SCRIPT_LD = """
OUTPUT_ARCH("riscv")

ENTRY(_start)

SECTIONS
{
    . = 0x80000000;

    .text : {
        *(.text.startup)
        *(.text)
    }

    .rodata : {
        *(.rodata)
    }

    .data : {
        *(.data)
    }

    .bss : {
        *(.bss)
    }
}
"""


class MiniProject:
    def __init__(
        self,
        toolchain: Toolchain,
        sources: List[Path],
        name: str | None,
        is_cleaning: bool = True,
    ) -> None:
        self.__toolchain = toolchain
        self.__sources = sources
        self.__name = name or self.__sources[0].stem
        self.__build_dir = Path(".")
        self.__is_cleaning = is_cleaning

    def __enter__(self) -> "MiniProject":
        self.__build_dir = Path(tempfile.mkdtemp())
        self.__build_dir /= self.__name

        dir = self.__build_dir
        dir.mkdir(exist_ok=True)

        for src in self.__sources:
            dst = dir / src.name
            shutil.copyfile(src, dst)

        makefile = dir / "Makefile"
        with open(makefile, "w") as f:
            f.write(self.__makefile)

        script_ld = dir / "script.ld"
        with open(script_ld, "w") as f:
            f.write(SCRIPT_LD)

        return self

    def __exit__(self, exc_type, exc_value, traceback) -> None:
        if self.__is_cleaning:
            loggy.info(f"Removing {self.__build_dir}...")
            shutil.rmtree(self.__build_dir)

    def build(self):
        loggy.info(
            f"Building {', '.join([f.name for f in self.__sources])} "
            + f"with cflags '{self.__toolchain.cflags}'..."
        )

        result = subprocess.run(
            ["make", self.executable_file],
            cwd=self.__build_dir,
            capture_output=True,
            text=True,
            check=False,
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"build at '{self.__build_dir}' returned {result.returncode}: {result.stderr}"
            )

    @property
    def name(self) -> str:
        return self.__name

    @property
    def executable_file(self) -> Path:
        return Path(f"{self.name}-riscv64.bin")

    @property
    def executable_path(self) -> Path:
        return self.__build_dir / self.executable_file

    @property
    def __makefile(self) -> str:
        sources = [f.name for f in self.__sources]
        objects = [f"{f}.o" for f in sources]

        p = self.__toolchain.path / "bin"
        cflags = self.__toolchain.cflags

        makefile = "# WARN. Generated by SimBa. Do not edit.\n"
        makefile += "\n"

        makefile += f"CFLAGS={cflags}\n"
        makefile += f"CC={p}/clang\n"
        makefile += f"AS={p}/clang\n"
        makefile += f"LD={p}/ld.lld\n"
        makefile += f"OBJDUMP={p}/llvm-objdump\n"
        makefile += f"OBJCOPY={p}/llvm-objcopy\n"
        makefile += f"AR={p}/llvm-ar\n"
        makefile += "\n"

        for source in sources:
            makefile += f"{source}.o: {" ".join(sources)}\n"
            makefile += f"\t{self.__compile(source)}\n"
            makefile += "\n"

        makefile += f"{self.executable_file}: Makefile script.ld {" ".join(objects)}\n"
        makefile += (
            f"\t$(LD) -T script.ld -o {self.executable_file} {" ".join(objects)}\n"
        )
        makefile += "\n"

        return makefile

    def __compile(self, source: str) -> str:
        if source.endswith(".c") or source.endswith(".ll") or source.endswith(".S"):
            return f"$(CC) $(CFLAGS) -c {source} -o {source}.o"
        raise ValueError(
            f"do not known how to compile {source}, .c/.ll/.S was expected"
        )
