import shutil
import subprocess
import tempfile
from pathlib import Path

from simba.args.toolchain import Toolchain
from simba.args.miniproject_config import MiniProjectConfig
from simba.args.input_data import BenchmarkInput
from simba.make.driver import generate_program, GenerationOptions

SCRIPT_LD = """
MEMORY {
  RAM (rwxa) : ORIGIN = 0x80000000, LENGTH = 64M
}

ENTRY(_start)

SECTIONS {
    .text : {
        *(.text.startup)
        *(.text)
    }

    .rodata : {
        *(.rodata)
    }

    .data : {
        *(.data)
    }

    .bss : {
        *(.bss)
    }

    /* stack && TLS, 128KB each */
    _stack_top = ALIGN(0x1000);
    . = _stack_top + 0x40000;
    _stack_pointer = .;
}
"""


TRAMPOLINE = """
.macro XiangShanTrap arg
    li a0, 0
    .word 0x5006b
.endm

.section .text.startup

.global _start
_start:
    #define STKSHIFT 17  // 128KB for each stack && TLS
    la tp, _stack_top
    add sp, zero, 1
    sll sp, sp, STKSHIFT
    add sp, sp, tp

    li t0, 0x2200 // FS and VC bits
    csrs mstatus, t0

    call main

    XiangShanTrap 0
"""


class MiniProject:
    def __init__(self, config: MiniProjectConfig) -> None:
        self.__toolchain = config.toolchain
        self.__sources = config.sources
        self.__name = self.__generate_name(
            config.name, self.__sources[0].stem, config.input_
        )
        self.__build_dir = Path(".")
        self.__is_cleaning = config.is_cleaning
        self.__is_trampoline_present = self.__is_trampoline_present_now()
        self.__input = config.input_

    def __enter__(self) -> "MiniProject":
        self.__build_dir = Path(tempfile.mkdtemp())
        self.__build_dir /= self.__name

        d = self.__build_dir
        d.mkdir(exist_ok=True)

        input_files_to_copy = (
            list(set(var_.input_path for var_ in self.__input.vars))
            if self.__input is not None
            else []
        )
        for src in self.__sources + input_files_to_copy:
            dst = d / src.name
            shutil.copyfile(src, dst)

        script_ld = d / "script.ld"
        with open(script_ld, "w", encoding="utf-8") as f:
            f.write(SCRIPT_LD)

        if not self.__is_trampoline_present:
            trampoline = d / "simba_trampoline.S"
            with open(trampoline, "w", encoding="utf-8") as f:
                f.write(TRAMPOLINE)
            self.__sources.append(trampoline)

        if self.__input is not None:
            bench = d / "main.c"
            options = GenerationOptions.from_variables(
                self.__input.vars,
                self.__input.iterations.warmup,
                self.__input.iterations.main,
            )
            benchcode = generate_program(
                function_name=self.__input.function.name,
                function_return_type=self.__input.function.return_type,
                options=options,
            )
            with open(bench, "w", encoding="utf-8") as f:
                f.write(benchcode)
            self.__sources.append(bench)

        makefile = d / "Makefile"
        with open(makefile, "w", encoding="utf-8") as f:
            f.write(self.__makefile)

        return self

    def __exit__(self, exc_type, exc_value, traceback) -> None:
        if self.__is_cleaning:
            shutil.rmtree(self.__build_dir)

    def build(self):
        result = subprocess.run(
            ["make", self.executable_file],
            cwd=self.__build_dir,
            capture_output=True,
            text=True,
            check=False,
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"build at '{self.__build_dir}' returned {result.returncode}: {result.stderr}"
            )

    @property
    def name(self) -> str:
        return self.__name

    @property
    def executable_file(self) -> Path:
        return Path(f"{self.name}-riscv64.bin")

    @property
    def executable_path(self) -> Path:
        return self.__build_dir / self.executable_file

    @property
    def toolchain(self) -> Toolchain:
        return self.__toolchain

    @property
    def is_trampoline_present(self) -> bool:
        return self.__is_trampoline_present

    def __is_trampoline_present_now(self) -> bool:
        for source in self.__sources:
            if source.suffix != ".S":
                continue

            with open(source, "r", encoding="utf-8") as f:
                content = f.read()

            if "_start" in content:
                return True

        return False

    @property
    def __makefile(self) -> str:
        sources = [Path(f.name) for f in self.__sources]
        objects = [f"{f.stem}.o" for f in sources]

        cc = self.__toolchain.path / "bin" / self.__toolchain.cc
        ld = self.__toolchain.path / "bin" / self.toolchain.ld
        cflags = self.__toolchain.cflags

        makefile = "# WARN. Generated by SimBa. Do not edit.\n"
        makefile += "\n"

        makefile += f"CFLAGS={cflags}\n"
        makefile += f"CC={cc}\n"
        makefile += f"LD={ld}\n"
        makefile += "\n"

        for source in sources:
            makefile += f"{source.stem}.o: {" ".join(map(str, sources))}\n"
            makefile += f"\t{self.__compile(source)}\n"
            makefile += "\n"

        makefile += f"{self.executable_file}: Makefile script.ld {" ".join(objects)}\n"
        makefile += (
            f"\t$(LD) -T script.ld {" ".join(objects)} -o {self.executable_file}\n"
        )
        makefile += "\n"

        return makefile

    def __compile(self, source: Path) -> str:
        def is_a(ext: str):
            return source.suffix == ext

        if is_a(".c") or is_a(".ll") or is_a(".S") or is_a(".h"):
            return f"$(CC) $(CFLAGS) -c {source} -o {source.stem}.o"
        raise ValueError(
            f"do not known how to compile {source}, .c/.ll/.S was expected"
        )

    def __generate_name(
        self, name: str | None, stem: str, input_: BenchmarkInput | None
    ) -> str:
        new_name = ""
        if name is not None:
            new_name = name
        else:
            return stem

        if input_ is None:
            return new_name

        suffix = []

        suffix.extend([input_.function.return_type, input_.function.name])
        for var_ in input_.vars:
            suffix.extend([var_.input_path.stem, var_.variable])

        return new_name + "_" + "_".join(suffix)
