from pathlib import Path
import shutil
import subprocess
import tempfile
from typing import List

from simba.args.toolchain import Toolchain
from simba.log import loggy

SCRIPT_LD = """
MEMORY {
  RAM (rwxa) : ORIGIN = 0x80000000, LENGTH = 64M
}

ENTRY(_start)

SECTIONS {
    .text : {
        *(.text.startup)
        *(.text)
    }

    .rodata : {
        *(.rodata)
    }

    .data : {
        *(.data)
    }

    .bss : {
        *(.bss)
    }
}
"""


TRAMPOLINE = """
.macro XiangShanTrap arg
    li a0, 0
    .word 0x5006b
.endm

.section .text.startup

.global _start
_start:
    li sp, 0x80001000

    call main

    XiangShanTrap 0
"""


class MiniProject:
    def __init__(
        self,
        toolchain: Toolchain,
        sources: List[Path],
        name: str | None,
        is_cleaning: bool = True,
    ) -> None:
        self.__toolchain = toolchain
        self.__sources = sources
        self.__name = name or self.__sources[0].stem
        self.__build_dir = Path(".")
        self.__is_cleaning = is_cleaning

    def __enter__(self) -> "MiniProject":
        self.__build_dir = Path(tempfile.mkdtemp())
        self.__build_dir /= self.__name

        loggy.info(f"Generating {self.__build_dir}...")

        dir = self.__build_dir
        dir.mkdir(exist_ok=True)

        for src in self.__sources:
            dst = dir / src.name
            shutil.copyfile(src, dst)

        script_ld = dir / "script.ld"
        with open(script_ld, "w") as f:
            f.write(SCRIPT_LD)

        if not self.__is_trampoline_present:
            trampoline = dir / "simba_trampoline.S"
            with open(trampoline, 'w') as f:
                f.write(TRAMPOLINE)
            self.__sources.append(trampoline)

        makefile = dir / "Makefile"
        with open(makefile, "w") as f:
            f.write(self.__makefile)

        return self

    def __exit__(self, exc_type, exc_value, traceback) -> None:
        if self.__is_cleaning:
            loggy.info(f"Removing {self.__build_dir}...")
            shutil.rmtree(self.__build_dir)

    def build(self):
        loggy.info(
            f"Building {', '.join([f.name for f in self.__sources])} "
            + f"with cflags '{self.__toolchain.cflags}'..."
        )

        result = subprocess.run(
            ["make", self.executable_file],
            cwd=self.__build_dir,
            capture_output=True,
            text=True,
            check=False,
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"build at '{self.__build_dir}' returned {result.returncode}: {result.stderr}"
            )

    @property
    def name(self) -> str:
        return self.__name

    @property
    def executable_file(self) -> Path:
        return Path(f"{self.name}-riscv64.bin")

    @property
    def executable_path(self) -> Path:
        return self.__build_dir / self.executable_file

    @property
    def __is_trampoline_present(self) -> bool:
        for source in self.__sources:
            if source.suffix != ".S":
                continue

            with open(source) as f:
                content = f.read()

            if "_start" in content:
                return True

        return False

    @property
    def __makefile(self) -> str:
        sources = [Path(f.name) for f in self.__sources]
        objects = [f"{f.stem}.o" for f in sources]

        p = self.__toolchain.path / "bin"
        cflags = self.__toolchain.cflags

        makefile = "# WARN. Generated by SimBa. Do not edit.\n"
        makefile += "\n"

        makefile += f"CFLAGS={cflags}\n"
        makefile += f"CC={p}/clang\n"
        makefile += f"LD={p}/ld.lld\n"
        makefile += "\n"

        for source in sources:
            makefile += f"{source.stem}.o: {" ".join(map(str, sources))}\n"
            makefile += f"\t{self.__compile(source)}\n"
            makefile += "\n"

        makefile += f"{self.executable_file}: Makefile script.ld {" ".join(objects)}\n"
        makefile += (
            f"\t$(LD) -T script.ld {" ".join(objects)} -o {self.executable_file}\n"
        )
        makefile += "\n"

        return makefile

    def __compile(self, source: Path) -> str:
        def is_a(ext: str):
            return source.suffix == ext

        if is_a(".c") or is_a(".ll") or is_a(".S"):
            return f"$(CC) $(CFLAGS) -c {source} -o {source.stem}.o"
        raise ValueError(
            f"do not known how to compile {source}, .c/.ll/.S was expected"
        )
